# Generated by Django 5.0.3 on 2024-03-10 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='pics')),
                ('location', models.CharField(max_length=100, null=True)),
                ('pricePerNight', models.IntegerField(null=True)),
                ('offer', models.IntegerField(default=0)),
                ('capacity', models.IntegerField(null=True)),
            ],
        ),
    ]
